#!/usr/bin/env bash
# Install nginx web server

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nSetting up minor details.\n"

# starting nginx service
sudo service nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# give user ownership to the website files
sudo chown -R "$USER": "$USER" /var/www/html
sudo chown -R 755 /var/www

# backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#create new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# restart nginx
sudo service nginx restart

echo -e "\nCompleted. \n"
