#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with resolution

cp /etc/hosts ~/hosts.new

if grep -q "127.0.0.2\s\+localhost" ~/hosts.new; then
    echo "localhost is already set to 127.0.0.2"
else
    sed -i '/127.0.0.1\s\+localhost/s/^/#/' ~/hosts.new
    echo "127.0.0.2 localhost" >> ~/hosts.new
fi

if grep -q "8.8.8.8\s\+facebook.com" ~/hosts.new; then
    echo "facebook.com is already set to 8.8.8.8"
else
    sed -i '/157.240.11.35\s\+facebook.com/s/^/#/' ~/hosts.new
    echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

sudo cp -f ~/hosts.new /etc/hosts

echo "Configuration complete."
