#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with resolution

cp /etc/hosts ~/hosts.new

	sed -i '/127.0.0.2\s\+localhost/s/^/#/' ~/host.new
	sed -i '/8.8.8.8\s\+facebook.com/s/^/#/' ~/host.new

cp -f ~/hosts.new /etc/hosts
